### ISSUE TITLE
[BUG] - Duplicate argument "self" in function definition

### ISSUE THREAD

**Issue by coltonbh** [postera-ai/rdkit-stubs#12]
After installing `rdkit-stubs` and running `mypy` on my code I get the following error:

```sh
/home/cbh/.cache/pypoetry/virtualenvs/qcio-RA1cVAvH-py3.8/lib/python3.8/site-packages/rdkit-stubs/Chem/rdMolDescriptors.pyi:247: error: Duplicate argument "self" in function definition
```

Here is the mistaken function signature:

```python
    def __init__(self, self: typing.Any, name: str, version: str) -> None:
        """
            C++ signature :
                void __init__(_object*,_object*,std::string,std::string)
        """
```

**Comment by bddap** [comment]
The [line of code ](https://github.com/postera-ai/rdkit-stubs/blob/b674d598b1c8185425a8eb8a89d19bf029291dab/rdkit-stubs/Chem/rdMolDescriptors.pyi#L247) indicated by that error message doesn't seem to mention `self` so it's hard to tell where the issue is.

Do you happen to know which type that constructor is attached to?

**Comment by coltonbh** [comment]
Yeah trying to figure out the weirdness in the auto-generated code. On my system it refers to this, which clearly has the error:

```python
class PythonPropertyFunctor(PropertyFunctor):
    """
    """
    __instance_size__: typing.ClassVar[int] = 64
    @staticmethod
    def __reduce__(*args, **kwargs):
        ...
    def __call__(self, mol: Mol) -> float:
        """
            Compute the property for the specified molecule
        
            C++ signature :
                double __call__((anonymous namespace)::PythonPropertyFunctor {lvalue},RDKit::ROMol)
        """
    def __init__(self, self: typing.Any, name: str, version: str) -> None: # THIS LINE HERE!!!
        """
            C++ signature :
                void __init__(_object*,_object*,std::string,std::string)
        """
```

**Comment by coltonbh** [comment]
The `rdkit-stubs.__init__.py` file I have is also different from the one you're showing on `master`. Something weird about how you're generating these stubs when I install `rdkit`??

```python
from __future__ import annotations
import logging as logging
import sys as sys
from .rdBase import *
__all__ = ['log_handler', 'logger', 'logging', 'rdBase', 'sys']
__version__: str = '2024.03.3'
log_handler: logging.StreamHandler  # value = <StreamHandler <stderr> (NOTSET)>
logger: logging.Logger  # value = <Logger rdkit (WARNING)>

```

This is python 3.8 BTW.

**Comment by coltonbh** [comment]
These stubs seem to have come a long with a `pip install rdkit` because I did not install them directly. Are they somehow bundled incorrectly with `rdkit`? Just noticed that when I run `pip install rdkit-stubs` then this issue goes away... Very strange!

**Comment by coltonbh** [comment]
So yes--full repro is

1. `pip install rdkit` (I have the latest version)
2. Run `mypy` on your project (whatever you are developing) -> You will get this error and have the code I pasted above at line 274 of the corresponding file.
3. `pip install rdkit-stubs`
4. Now this issue is gone...

So it appears builds of `rdkit` are packaged with some old/bad version of `rdkit-stubs` even though it's not listed as a dependency? Something strange like this...

**Comment by bddap** [comment]
Rdkit recently added its own stubs. https://greglandrum.github.io/rdkit-blog/posts/2024-03-08-docstring-stubs.html (exiting! this `rdkit-stubs` package might be obsolete soon!). I suspect the type error is a problem with the stubs genterated by rdkit.

Looks like this type error is cased by the stubs that were autogenerated for PythonPropertyFunctor.

This is where the function is registered on the c++ side: https://github.com/rdkit/rdkit/blob/cba05a9b3a4fe38f50100b5cc5d17890517be526/Code/GraphMol/Descriptors/Wrap/rdMolDescriptors.cpp#L1627

**Comment by coltonbh** [comment]
Ohh. That's a little nasty that they gave it the same name as this project so figuring out what's broken is a bit ugly... I'll resubit the issue there!

**Comment by coltonbh** [comment]
Closing since this is an issue with the `rdkit` stubs, not this library. Thanks for your help sorting this out! Added comments to [this issue](https://github.com/rdkit/rdkit/issues/7583) and it appears [this PR](https://github.com/rdkit/rdkit/pull/7595) is an attempt at fixing this issue.
